# Default values for deploy-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.50.11/seyana/deploy-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  workingDir: /testfiles
  command:
    [
      "/bin/java",
      "-jar",
      "-Dspring.config.location=/configs/application.properties",
      "deploy-test.jar",
    ]

imagePullSecrets:
  harborsecret:
    create: true
  test-secret:
nameOverride: ""
fullnameOverride: ""

imageCredentials:
  harborsecret:
    registry: 192.168.50.11
    username: seyana
    password: Seyana0831
  #email: neil.yu@dynasafe.com.tw

environment: test

serverProperties:
  connection.target: http://10.255.78.57:3000/id/OMS_TEST/test
  connection.Probability: 20
  connection.enabled: false
  # version: v6.2.31

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

deployment:
  revisionHistoryLimit: 3

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9527

ingress:
  enabled: true
  selfHostsEnabled: true
  customHostsEnabled: false

  # selfHosts setting
  hostname: ""
  # hostname: cicd-ingress.deploy-test

  # customHosts setting
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cicd-ingress.deploy-test02
      paths:
        - path: /
          backend:
            serviceName: test-deploy-test
            servicePort: 9527
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
