{{- if eq .Values.environment "dev" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-test.fullname" . }}-dev
data:
  application.properties: |
  {{- range $key, $value := .Values.serverProperties }}
    {{ $key }}={{ $value }}
  {{- end }}
    environment=DEV
    server.address=0.0.0.0
    server.port=9528
    server.http.port=9527
    mutate.command=[{ \"op\": \"add\", \"path\": \"/metadata/labels/foo\", \"value\": \"bar\" }]
    spring.thymeleaf.cache=false
    spring.thymeleaf.enabled=true
    spring.thymeleaf.prefix=classpath:/templates/
    spring.thymeleaf.suffix=.html
    spring.jmx.enabled=true
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.metrics.enabled=true
    management.endpoint.env.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always
    management.metrics.enable.all=false
    management.endpoint.prometheus.enabled=true
    server.ssl.enabled=true
    server.ssl.key-store-type=PKCS12
    server.ssl.key-store=classpath:keystore/ca.p12
    server.ssl.key-store-password=changeit
{{- end }}